package aisdk

import (
	"encoding/json"

	"github.com/nrbrd/ai-sdk-legacy/provider"
)

// TextStreamPart is the interface for all orchestration-level stream events.
// StreamText emits these on FullStream(). Consumers type-switch to handle
// specific event types.
//
// This is the middle layer between provider.StreamPart (raw provider events)
// and UIMessageChunk (SSE wire format).
type TextStreamPart interface {
	textStreamPart()
}

// StreamStart signals the beginning of a StreamText orchestration.
type StreamStart struct{}

func (StreamStart) textStreamPart() {}

// StreamStartStep signals the beginning of a new step in the orchestration loop.
type StreamStartStep struct {
	Warnings []provider.Warning
	Request  *provider.RequestMetadata
}

func (StreamStartStep) textStreamPart() {}

// StreamFinishStep signals the end of a step with usage and metadata.
type StreamFinishStep struct {
	Response         *provider.ResponseMetadata
	Usage            *provider.Usage
	FinishReason     provider.FinishReason
	ProviderMetadata provider.ProviderMetadata
}

func (StreamFinishStep) textStreamPart() {}

// StreamFinish signals the end of the entire StreamText orchestration.
type StreamFinish struct {
	FinishReason provider.FinishReason
	TotalUsage   *provider.Usage
}

func (StreamFinish) textStreamPart() {}

// StreamAbort signals that the stream was cancelled.
type StreamAbort struct {
	Reason string
}

func (StreamAbort) textStreamPart() {}

// StreamError carries an error from the provider or orchestration.
type StreamError struct {
	Error error
}

func (StreamError) textStreamPart() {}

// StreamRaw carries unprocessed provider data (when IncludeRawChunks is set).
type StreamRaw struct {
	RawValue json.RawMessage
}

func (StreamRaw) textStreamPart() {}

// StreamCustom carries provider-specific custom content.
type StreamCustom struct {
	Kind             string
	ProviderMetadata provider.ProviderMetadata
}

func (StreamCustom) textStreamPart() {}

// StreamTextStart opens a text block.
type StreamTextStart struct {
	ID               string
	ProviderMetadata provider.ProviderMetadata
}

func (StreamTextStart) textStreamPart() {}

// StreamTextDelta carries incremental text within a block.
type StreamTextDelta struct {
	ID               string
	Text             string
	ProviderMetadata provider.ProviderMetadata
}

func (StreamTextDelta) textStreamPart() {}

// StreamTextEnd closes a text block.
type StreamTextEnd struct {
	ID               string
	ProviderMetadata provider.ProviderMetadata
}

func (StreamTextEnd) textStreamPart() {}

// StreamReasoningStart opens a reasoning block.
type StreamReasoningStart struct {
	ID               string
	ProviderMetadata provider.ProviderMetadata
}

func (StreamReasoningStart) textStreamPart() {}

// StreamReasoningDelta carries incremental reasoning within a block.
type StreamReasoningDelta struct {
	ID               string
	Text             string
	ProviderMetadata provider.ProviderMetadata
}

func (StreamReasoningDelta) textStreamPart() {}

// StreamReasoningEnd closes a reasoning block.
type StreamReasoningEnd struct {
	ID               string
	ProviderMetadata provider.ProviderMetadata
}

func (StreamReasoningEnd) textStreamPart() {}

// StreamToolInputStart opens tool argument streaming.
type StreamToolInputStart struct {
	ID               string
	ToolName         string
	ProviderExecuted bool
	Dynamic          *bool
	Title            string
	ProviderMetadata provider.ProviderMetadata
}

func (StreamToolInputStart) textStreamPart() {}

// StreamToolInputDelta carries incremental tool arguments.
type StreamToolInputDelta struct {
	ID               string
	Delta            string
	ProviderMetadata provider.ProviderMetadata
}

func (StreamToolInputDelta) textStreamPart() {}

// StreamToolInputEnd closes tool argument streaming.
type StreamToolInputEnd struct {
	ID               string
	ProviderMetadata provider.ProviderMetadata
}

func (StreamToolInputEnd) textStreamPart() {}

// StreamSource carries a reference source (URL or document).
type StreamSource struct {
	Source Source
}

func (StreamSource) textStreamPart() {}

// StreamFile carries a file generated by the model.
type StreamFile struct {
	File             GeneratedFile
	ProviderMetadata provider.ProviderMetadata
}

func (StreamFile) textStreamPart() {}

// StreamReasoningFile carries a file generated as part of model reasoning.
type StreamReasoningFile struct {
	File             GeneratedFile
	ProviderMetadata provider.ProviderMetadata
}

func (StreamReasoningFile) textStreamPart() {}

// StreamToolCall carries a complete tool call (input parsed from string).
type StreamToolCall struct {
	ToolCallID       string
	ToolName         string
	Input            json.RawMessage
	Invalid          bool
	Error            error
	ProviderExecuted bool
	Dynamic          *bool
	Title            string
	ProviderMetadata provider.ProviderMetadata
	uiDynamic        *bool
	useUIDynamic     bool
}

func (StreamToolCall) textStreamPart() {}

// StreamToolApprovalRequest carries a request for user approval before tool execution.
type StreamToolApprovalRequest struct {
	ApprovalID       string
	ToolCallID       string
	ToolName         string
	Input            json.RawMessage
	Signature        string
	ProviderExecuted bool
	Dynamic          *bool
	Title            string
	IsAutomatic      bool
	ProviderMetadata provider.ProviderMetadata
}

func (StreamToolApprovalRequest) textStreamPart() {}

// StreamToolApprovalResponse carries a user approval or denial decision.
type StreamToolApprovalResponse struct {
	ApprovalID       string
	ToolCallID       string
	ToolName         string
	Approved         bool
	Reason           string
	ProviderExecuted bool
	Dynamic          *bool
	Title            string
	ProviderMetadata provider.ProviderMetadata
}

func (StreamToolApprovalResponse) textStreamPart() {}

// StreamToolOutputDenied carries a denied tool execution marker.
type StreamToolOutputDenied struct {
	ToolCallID string
	ToolName   string
}

func (StreamToolOutputDenied) textStreamPart() {}

// StreamToolResult carries a tool execution result (local or provider-executed).
type StreamToolResult struct {
	ToolCallID       string
	ToolName         string
	Input            json.RawMessage
	Output           json.RawMessage
	IsError          bool
	ProviderExecuted bool
	Dynamic          *bool
	Preliminary      bool
	Title            string
	ProviderMetadata provider.ProviderMetadata
}

func (StreamToolResult) textStreamPart() {}

// StreamToolError carries a tool execution failure.
type StreamToolError struct {
	ToolCallID       string
	ToolName         string
	Input            json.RawMessage
	Error            error
	ProviderExecuted bool
	Dynamic          *bool
	Title            string
	ProviderMetadata provider.ProviderMetadata
	uiDynamic        *bool
	useUIDynamic     bool
}

func (StreamToolError) textStreamPart() {}
