package aisdk

import (
	"encoding/base64"
	"fmt"

	"github.com/nrbrd/ai-sdk-legacy/provider"
)

// Source represents a reference source (URL or document) in the generated output.
type Source struct {
	SourceType       provider.SourceType       `json:"sourceType"`
	ID               string                    `json:"id,omitempty"`
	URL              string                    `json:"url,omitempty"`
	Title            string                    `json:"title,omitempty"`
	MediaType        string                    `json:"mediaType,omitempty"`
	Filename         string                    `json:"filename,omitempty"`
	ProviderMetadata provider.ProviderMetadata `json:"providerMetadata,omitempty"`
}

// GeneratedFile represents a file generated by the model.
type GeneratedFile struct {
	Data      []byte `json:"-"`
	Base64    string `json:"-"`
	MediaType string `json:"mediaType"`
}

func (f GeneratedFile) DataURL() string {
	if f.MediaType == "" {
		return ""
	}
	data := f.Base64
	if f.Data != nil {
		data = base64.StdEncoding.EncodeToString(f.Data)
	} else if data == "" {
		return ""
	}
	return fmt.Sprintf("data:%s;base64,%s", f.MediaType, data)
}

func generatedFileFromStreamData(data *provider.StreamFileData, mediaType string) GeneratedFile {
	file := GeneratedFile{MediaType: mediaType}
	if data == nil {
		return file
	}
	if data.Type == provider.StreamFileDataTypeData || data.Bytes != nil || data.Base64 != "" {
		if data.Bytes != nil {
			file.Data = data.Bytes
		} else if data.Base64 != "" {
			file.Base64 = data.Base64
		} else {
			file.Data = []byte{}
		}
	} else {
		file.Base64 = data.URL
	}
	return file
}

func generatedFileData(file GeneratedFile) *provider.DataContent {
	if file.Data != nil {
		return &provider.DataContent{Bytes: file.Data}
	}
	if file.Base64 != "" {
		return &provider.DataContent{Base64: file.Base64}
	}
	return nil
}

func generatedFileFromDataContent(data *provider.DataContent, mediaType string) GeneratedFile {
	file := GeneratedFile{MediaType: mediaType}
	if data == nil {
		return file
	}
	if data.Bytes != nil {
		file.Data = data.Bytes
	} else if data.Base64 != "" {
		file.Base64 = data.Base64
	} else {
		file.Base64 = data.URL
	}
	return file
}

// ReasoningOutput is a text or file artifact generated as model reasoning.
type ReasoningOutput interface {
	reasoningOutput()
}

// ReasoningTextOutput represents generated reasoning text.
type ReasoningTextOutput struct {
	Text             string                    `json:"text"`
	ProviderMetadata provider.ProviderMetadata `json:"providerMetadata,omitempty"`
}

func (ReasoningTextOutput) reasoningOutput() {}

// ReasoningFileOutput represents a file generated as model reasoning.
type ReasoningFileOutput struct {
	File             GeneratedFile             `json:"file"`
	ProviderMetadata provider.ProviderMetadata `json:"providerMetadata,omitempty"`
}

func (ReasoningFileOutput) reasoningOutput() {}
